
package com.example.bank;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-09-23T16:51:21.967+03:00
 * Generated source version: 4.0.3
 */

@WebFault(name = "accountNotFoundException", targetNamespace = "http://bank.example.com/")
public class AccountNotFoundFault extends Exception {

    private com.example.bank.AccountNotFoundException faultInfo;

    public AccountNotFoundFault() {
        super();
    }

    public AccountNotFoundFault(String message) {
        super(message);
    }

    public AccountNotFoundFault(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public AccountNotFoundFault(String message, com.example.bank.AccountNotFoundException accountNotFoundException) {
        super(message);
        this.faultInfo = accountNotFoundException;
    }

    public AccountNotFoundFault(String message, com.example.bank.AccountNotFoundException accountNotFoundException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = accountNotFoundException;
    }

    public com.example.bank.AccountNotFoundException getFaultInfo() {
        return this.faultInfo;
    }
}
