package com.example.bank;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-09-23T16:51:21.973+03:00
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://bank.example.com/", name = "BankServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BankServicePortType {

    @WebMethod
    @WebResult(name = "transferResponse", targetNamespace = "http://bank.example.com/", partName = "parameters")
    public TransferResponse transfer(

        @WebParam(partName = "parameters", name = "transferRequest", targetNamespace = "http://bank.example.com/")
        TransferRequest parameters
    ) throws InsufficientFundsFault, AccountNotFoundFault;

    @WebMethod
    @WebResult(name = "getTransactionHistoryResponse", targetNamespace = "http://bank.example.com/", partName = "parameters")
    public GetTransactionHistoryResponse getTransactionHistory(

        @WebParam(partName = "parameters", name = "getTransactionHistoryRequest", targetNamespace = "http://bank.example.com/")
        GetTransactionHistoryRequest parameters
    ) throws AccountNotFoundFault;

    @WebMethod
    @WebResult(name = "getAccountResponse", targetNamespace = "http://bank.example.com/", partName = "parameters")
    public GetAccountResponse getAccount(

        @WebParam(partName = "parameters", name = "getAccountRequest", targetNamespace = "http://bank.example.com/")
        GetAccountRequest parameters
    ) throws AccountNotFoundFault;
}
