package com.example.bank;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-09-23T16:51:21.982+03:00
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "BankService",
                  wsdlLocation = "file:/Applications/WSDL_EXAMPLE/example.wsdl",
                  targetNamespace = "http://bank.example.com/")
public class BankService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://bank.example.com/", "BankService");
    public final static QName BankServicePort = new QName("http://bank.example.com/", "BankServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Applications/WSDL_EXAMPLE/example.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BankService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Applications/WSDL_EXAMPLE/example.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BankService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BankService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BankService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BankService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BankService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns BankServicePortType
     */
    @WebEndpoint(name = "BankServicePort")
    public BankServicePortType getBankServicePort() {
        return super.getPort(BankServicePort, BankServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankServicePortType
     */
    @WebEndpoint(name = "BankServicePort")
    public BankServicePortType getBankServicePort(WebServiceFeature... features) {
        return super.getPort(BankServicePort, BankServicePortType.class, features);
    }

}
