
package com.example.bank;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.3
 * 2025-09-23T16:51:21.958+03:00
 * Generated source version: 4.0.3
 */

@WebFault(name = "insufficientFundsException", targetNamespace = "http://bank.example.com/")
public class InsufficientFundsFault extends Exception {

    private com.example.bank.InsufficientFundsException faultInfo;

    public InsufficientFundsFault() {
        super();
    }

    public InsufficientFundsFault(String message) {
        super(message);
    }

    public InsufficientFundsFault(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InsufficientFundsFault(String message, com.example.bank.InsufficientFundsException insufficientFundsException) {
        super(message);
        this.faultInfo = insufficientFundsException;
    }

    public InsufficientFundsFault(String message, com.example.bank.InsufficientFundsException insufficientFundsException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = insufficientFundsException;
    }

    public com.example.bank.InsufficientFundsException getFaultInfo() {
        return this.faultInfo;
    }
}
